name: Build app and deploy to Oracle

on:
  #监听push操作
  push:
    branches:
      # mian分支，你也可以改成其他分支
      - dev
jobs:
  # 任务ID
  build:
    # 运行环境
    runs-on: ubuntu-latest
    # 步骤
    steps:
    # 使用别人的action
    - uses: actions/checkout@v2
    # 步骤名称
    - name: npm install
      # 步骤执行指令
      run: npm install
    - name: npm run build
      run: npm run build
    # 命名这个任务为发布Deploy
    - name: Deploy
      # 因为构建之后，需要把代码上传到服务器上，所以需要连接到ssh，并且做一个拷贝操作
      uses: cross-the-world/scp-pipeline@master
      env:
        # 私钥
        SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        # 源目录
        SOURCE:  ./docs/.vuepress/dist/*
        # 服务器ip：换成你的服务器IP
        REMOTE_HOST: ${{ secrets.USER_HOST }}
         # 用户
        REMOTE_USER: 'root'
        WELCOME: "ssh scp ssh pipelines"
        LASTSSH: "Doing something after copying"
        # 目标地址
        TARGET: /www/wwwroot/docs/dist
      with:
        connect_timeout: 10s
        
